language: go
sudo: required
dist: trusty

services:
  - docker

go:
  - 1.8.x

go_import_path: k8s.io/frakti

before_install:
  - hack/install-docker.sh

install:
  - docker run -v /usr/local/bin:/target jpetazzo/nsenter
  - go install -v $(go list ./... | grep -v /vendor/)
  - hack/install-protoc.sh
  - hack/install-hypercontainer.sh
  - make ginkgo && make frakti
  - hack/verify-all.sh -v

jobs:
  include:
    - stage: Unit Test
      script: hack/test-go.sh
    - stage: End to End Test
      script: hack/test-e2e.sh

